#                                                                                                           Deep Learning using PyTorch

Implementing Machine Learning based algorithm to train Linear Model to fit a set of data points.

Getting comfortable making predictions by using Linear Model.


Machine Leraning is the concept of building algorithms that can learn based on experience to detect and predict meaningful patterns. 

In Supervised Learning, algorithms are trained to make use of labeled data. Once introduced to new input, the algoritms are able to predict a corresponding output.

In [9]:
# import relevant Torch Library
!pip3 install torch

In [0]:
import torch
from torch.nn import Linear

In [0]:
w = torch.tensor(3.0, requires_grad=True) #weight
b = torch.tensor(1.0, requires_grad=True)#bias



In [0]:
def forward(x): # forward-function with one argument
  y =w*x + b
  return y

In [7]:
x =torch.tensor(2)
forward(x)

tensor(7., grad_fn=<AddBackward0>)

In [8]:
x = torch.tensor([[4],[7]]) # making predictins for 4 and 7, two separate inputs
forward(x)

tensor([[13],
        [22]], grad_fn=<AddBackward0>)





*   13 is prediction for 4;
*  22 is prediction for 7




In [13]:
torch.manual_seed(1) # set a seed for generating random number for the Linear Class

In [15]:
model = Linear(in_features =1, out_features=1) # for every single input calculate single ouput
print(model.bias, model.weight) # obtain the optimal parameters to fit the data

Parameter containing:
tensor([-0.4414], requires_grad=True) Parameter containing:
tensor([[0.5153]], requires_grad=True)


In [16]:
x = torch.tensor([2.0]) # float number
model22 is prediction for 7(x) # passing x as input

tensor([0.5891], grad_fn=<AddBackward0>)

In [17]:
#@ passing multiple input
x = torch.tensor([[2.0],[3.3]])
model(x)

tensor([[0.5891],
        [1.2590]], grad_fn=<AddmmBackward>)

In [0]:
import torch.nn as nn

In [0]:
# Linear Regression Class
# creating objects, new instances of Linear Regression Class
# class is followed by init method(constructer, initializer)
class LR(nn.Module):
  def __init__(self,input_size,output_size):
    super().__init__() # template to create custom class
    self.Linear = nn.Linear(input_size,output_size)
  def forward(self, x):
    pred = self.Linear(x)
    return pred

In [36]:
torch.manual_seed(1)
model = LR(1,1)
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


weight equals 0.5153
bias equals -0.4414

In [39]:
x = torch.tensor([1.0]) # single input, single output
print(model.forward(x))

tensor([0.0739], grad_fn=<AddBackward0>)


In [40]:
x = torch.tensor([[1.0],[2.0]]) # multiple input, multiple output
print(model.forward(x))

tensor([[0.0739],
        [0.5891]], grad_fn=<AddmmBackward>)
