<a href="https://colab.research.google.com/github/reallygooday/60daysofudacity/blob/master/Federated_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://colab.research.google.com/drive/1jwN3C_Pn6gH7qPYFNrwhzHULbogKLJX3#scrollTo=UDMD6YnRf6ry


In [0]:
!pip install syft

     |████████████████████████████████| 225kB 2.8MB/s 
     |████████████████████████████████| 389kB 41.2MB/s 
     |████████████████████████████████| 204kB 42.4MB/s 
     |████████████████████████████████| 81kB 26.5MB/s 
     |████████████████████████████████| 256kB 43.6MB/s 
     |████████████████████████████████| 460kB 38.5MB/s 
     |████████████████████████████████| 2.1MB 38.6MB/s 
     |████████████████████████████████| 266kB 44.3MB/s 
     |████████████████████████████████| 51kB 16.8MB/s 
     |████████████████████████████████| 122kB 42.4MB/s 
  Created wheel for zstd: filename=zstd-1.4.1.0-cp36-cp36m-linux_x86_64.whl size=1067050 sha256=7a0ff30a0d7a32a567b91aeb22b3c802404d2278795809e76d7c5b18ad990266
  Stored in directory: /root/.cache/pip/wheels/66/3f/ee/ac08c81af7c1b24a80c746df669ea3cb37542d27877d66ccf4
  Created wheel for pyyaml: filename=PyYAML-5.1.2-cp36-cp36m-linux_x86_64.whl size=44105 sha256=f74a3b353616d6a5f2a6f5e68db22f9930d6e5389064b130da02bfb46acfbb5a
  Stored in di

In [1]:
!pip install numpy

In [8]:
!pip install --upgrade --force-reinstall zstd

     |████████████████████████████████| 460kB 9.0MB/s 
  Created wheel for zstd: filename=zstd-1.4.1.0-cp36-cp36m-linux_x86_64.whl size=1067077 sha256=ea0273a0e8a79125522bb1ae71e129076fed6846893d19c13d407b707c372d9e
  Stored in directory: /root/.cache/pip/wheels/66/3f/ee/ac08c81af7c1b24a80c746df669ea3cb37542d27877d66ccf4
Successfully built zstd


https://github.com/OpenMined/PySyft

In [0]:
import torch as th

In [3]:

x = th.tensor([1,2,3,4,5])
x

tensor([1, 2, 3, 4, 5])

In [0]:
y = x + x

In [5]:
print(y)

tensor([ 2,  4,  6,  8, 10])


In [12]:
!pip3 install syft

     |████████████████████████████████| 225kB 9.3MB/s 
     |████████████████████████████████| 2.1MB 44.6MB/s 
     |████████████████████████████████| 256kB 53.9MB/s 
     |████████████████████████████████| 204kB 49.8MB/s 
     |████████████████████████████████| 389kB 43.4MB/s 
     |████████████████████████████████| 81kB 29.5MB/s 
     |████████████████████████████████| 266kB 45.8MB/s 
     |████████████████████████████████| 51kB 21.4MB/s 
     |████████████████████████████████| 122kB 52.2MB/s 
  Created wheel for pyyaml: filename=PyYAML-5.1.2-cp36-cp36m-linux_x86_64.whl size=44105 sha256=b8e1228f45b751510efe0d84b508367a02f773aac9130e375f99850ffe34b9b8
  Stored in directory: /root/.cache/pip/wheels/d9/45/dd/65f0b38450c47cf7e5312883deb97d065e030c5cca0a365030
Successfully built pyyaml
  Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13
  Found existing installation: msgpack 0.5.6
    Uninstalling msgpack-0.5.6:
      Succes

In [13]:
import syft as sy

W0804 16:29:18.806474 140658818156416 secure_random.py:26] Falling back to insecure randomness since the required custom op could not be found for the installed version of TensorFlow. Fix this by compiling custom ops. Missing file was '/usr/local/lib/python3.6/dist-packages/tf_encrypted/operations/secure_random/secure_random_module_tf_1.14.0.so'
W0804 16:29:18.824997 140658818156416 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/tf_encrypted/session.py:26: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.



In [0]:
hook = sy.TorchHook(th)

In [15]:
th.tensor([1,2,3,4,5])

tensor([1, 2, 3, 4, 5])

# Basic Remote Execution in PySyft
PySyft => Remote PyTorch



In [0]:
bob = sy.VirtualWorker(hook, id="bob")

In [17]:
bob._objects

{}

In [0]:
x = th.tensor([1,2,3,4,5])

In [0]:
x = x.send(bob)

In [20]:
bob._objects

{82710931538: tensor([1, 2, 3, 4, 5])}

In [21]:
x.location

<VirtualWorker id:bob #objects:1>

In [22]:
x.id_at_location

82710931538

In [26]:
x.id

64676332238

In [25]:
x.owner

<VirtualWorker id:me #objects:0>

In [27]:
hook.local_worker

<VirtualWorker id:me #objects:0>

In [28]:
x

(Wrapper)>[PointerTensor | me:64676332238 -> bob:82710931538]

In [0]:

x = x.get()
x

In [29]:

bob._objects

{82710931538: tensor([1, 2, 3, 4, 5])}

# Playing with Remote Tensors


 Do .send() and .get() a tensor to TWO workers by calling .send(bob,alice). This will first require the creation of another VirtualWorker called alice.

In [0]:
alice = sy.VirtualWorker(hook, id="alice")

In [0]:

x = th.tensor([1,2,3,4,5])

In [0]:

x_ptr = x.send(bob, alice)

In [33]:
x_ptr.get()

[tensor([1, 2, 3, 4, 5]), tensor([1, 2, 3, 4, 5])]

In [0]:

x = th.tensor([1,2,3,4,5]).send(bob, alice)

In [35]:
x.get(sum_results=True)

tensor([ 2,  4,  6,  8, 10])

# Introducing Remote Arithmetic


In [0]:
x = th.tensor([1,2,3,4,5]).send(bob)
y = th.tensor([1,1,1,1,1]).send(bob)

In [57]:
x

(Wrapper)>[PointerTensor | me:74248584054 -> bob:53910305579]

In [39]:
y

(Wrapper)>[PointerTensor | me:32321368133 -> bob:18970555093]

In [0]:
z = x + y

In [41]:
z

(Wrapper)>[PointerTensor | me:28000294166 -> bob:64085232185]

In [42]:
z = z.get()
z

tensor([2, 3, 4, 5, 6])

In [43]:
z = th.add(x,y)
z

(Wrapper)>[PointerTensor | me:27898424387 -> bob:9850872715]

In [0]:
z = z.get()
z

In [0]:

x = th.tensor([1.,2,3,4,5], requires_grad=True).send(bob)
y = th.tensor([1.,1,1,1,1], requires_grad=True).send(bob)

In [0]:
z = (x + y).sum()

In [47]:
z.backward()

(Wrapper)>[PointerTensor | me:98804661531 -> bob:96003260034]

In [0]:
x = x.get()

In [59]:
x

tensor([1, 2, 3, 4, 5])

In [0]:
x.grad

# Simple Linear Model


In [0]:
Create a simple linear model which will solve for the following dataset below. You should use only Variables and .backward() to do so (no optimizers or nn.Modules). Furthermore, you must do so with both the data and the model being located on Bob's machine.

In [0]:
input = th.tensor([[1.,1],[0,1,],[1,0],[0,0]], requires_grad=True).send(bob)
target = th.tensor([[1.],[1],[0],[0]], requires_grad=True).send(bob)

In [0]:
weights = th.tensor([[0.],[0.]], requires_grad=True).send(bob)

In [63]:
for i in range(10):

    pred = input.mm(weights)

    loss = ((pred - target)**2).sum()

    loss.backward()

    weights.data.sub_(weights.grad * 0.1)
    weights.grad *= 0

    print(loss.get().data)

tensor(2.)
tensor(0.5600)
tensor(0.2432)
tensor(0.1372)
tensor(0.0849)
tensor(0.0538)
tensor(0.0344)
tensor(0.0220)
tensor(0.0141)
tensor(0.0090)


# Garbage Collection and Common Errors

In [0]:
bob = bob.clear_objects()

In [65]:
bob._objects

{}

In [0]:
x = th.tensor([1,2,3,4,5]).send(bob)

In [67]:
bob._objects

{32953481073: tensor([1, 2, 3, 4, 5])}

In [0]:
del x

In [69]:
bob._objects

{}

In [0]:
x = th.tensor([1,2,3,4,5]).send(bob)

In [71]:
bob._objects

{5899958707: tensor([1, 2, 3, 4, 5])}

In [0]:
x = "asdf"

In [73]:
bob._objects

{}

In [0]:
x = th.tensor([1,2,3,4,5]).send(bob)

In [75]:
x

(Wrapper)>[PointerTensor | me:87734769815 -> bob:45345673736]

In [0]:
bob._objects

In [0]:
x = "asdf"

In [77]:
bob._objects

{45345673736: tensor([1, 2, 3, 4, 5])}

In [0]:
del x

In [79]:
bob._objects

{45345673736: tensor([1, 2, 3, 4, 5])}

In [80]:
bob = bob.clear_objects()
bob._objects

{}

In [0]:
for i in range(1000):
    x = th.tensor([1,2,3,4,5]).send(bob)

In [82]:
bob._objects

{51840578077: tensor([1, 2, 3, 4, 5])}

In [0]:

x = th.tensor([1,2,3,4,5]).send(bob)
y = th.tensor([1,1,1,1,1])

In [0]:
#z = x + y

In [0]:
x = th.tensor([1,2,3,4,5]).send(bob)
y = th.tensor([1,1,1,1,1]).send(alice)

In [88]:
!z = x + y

/bin/bash: z: command not found


# Toy Federated Learning

Training a toy model the centralized way. This is about a simple as models get. We first need:

a toy dataset
a model
some basic training logic for training a model to fit the data.

In [0]:
from torch import nn, optim

In [0]:
# A Toy Dataset
data = th.tensor([[1.,1],[0,1],[1,0],[0,0]], requires_grad=True)
target = th.tensor([[1.],[1], [0], [0]], requires_grad=True)

In [0]:
# A Toy Model
model = nn.Linear(2,1)

In [0]:
opt = optim.SGD(params=model.parameters(), lr=0.1)

In [95]:

def train(iterations=20):
    for iter in range(iterations):
        opt.zero_grad()

        pred = model(data)

        loss = ((pred - target)**2).sum()

        loss.backward()

        opt.step()

        print(loss.data)
        
train()

tensor(4.2254)
tensor(0.5119)
tensor(0.1788)
tensor(0.1157)
tensor(0.0837)
tensor(0.0616)
tensor(0.0456)
tensor(0.0339)
tensor(0.0253)
tensor(0.0190)
tensor(0.0143)
tensor(0.0108)
tensor(0.0081)
tensor(0.0061)
tensor(0.0047)
tensor(0.0035)
tensor(0.0027)
tensor(0.0020)
tensor(0.0016)
tensor(0.0012)


In [0]:
data_bob = data[0:2].send(bob)
target_bob = target[0:2].send(bob)

In [0]:
data_alice = data[2:4].send(alice)
target_alice = target[2:4].send(alice)

In [0]:

datasets = [(data_bob, target_bob), (data_alice, target_alice)]

In [0]:
def train(iterations=20):

    model = nn.Linear(2,1)
    opt = optim.SGD(params=model.parameters(), lr=0.1)
    
    for iter in range(iterations):

        for _data, _target in datasets:

            # send model to the data
            model = model.send(_data.location)

            # do normal training
            opt.zero_grad()
            pred = model(_data)
            loss = ((pred - _target)**2).sum()
            loss.backward()
            opt.step()

            # get smarter model back
            model = model.get()

            print(loss.get())

In [100]:
train()

tensor(2.8716, requires_grad=True)
tensor(0.0280, requires_grad=True)
tensor(0.0381, requires_grad=True)
tensor(0.0190, requires_grad=True)
tensor(0.0171, requires_grad=True)
tensor(0.0135, requires_grad=True)
tensor(0.0117, requires_grad=True)
tensor(0.0096, requires_grad=True)
tensor(0.0081, requires_grad=True)
tensor(0.0069, requires_grad=True)
tensor(0.0057, requires_grad=True)
tensor(0.0051, requires_grad=True)
tensor(0.0041, requires_grad=True)
tensor(0.0037, requires_grad=True)
tensor(0.0029, requires_grad=True)
tensor(0.0028, requires_grad=True)
tensor(0.0021, requires_grad=True)
tensor(0.0021, requires_grad=True)
tensor(0.0015, requires_grad=True)
tensor(0.0016, requires_grad=True)
tensor(0.0011, requires_grad=True)
tensor(0.0012, requires_grad=True)
tensor(0.0008, requires_grad=True)
tensor(0.0009, requires_grad=True)
tensor(0.0006, requires_grad=True)
tensor(0.0007, requires_grad=True)
tensor(0.0004, requires_grad=True)
tensor(0.0005, requires_grad=True)
tensor(0.0003, requi

# Advanced Remote Execution Tools

In the last section we trained a toy model using Federated Learning. We did this by calling .send() and .get() on our model, sending it to the location of training data, updating it, and then bringing it back. However, at the end of the example we realized that we needed to go a bit further to protect people privacy. Namely, we want to average the gradients BEFORE calling .get(). That way, we won't ever see anyone's exact gradient (thus better protecting their privacy!!!)

But, in order to do this, we need a few more pieces:

use a pointer to send a Tensor directly to another worker
And in addition, while we're here, we're going to learn about a few more advanced tensor operations as well which will help us both with this example and a few in the future!

In [0]:
bob.clear_objects()
alice.clear_objects()

In [0]:
x = th.tensor([1,2,3,4,5]).send(bob)

In [0]:
x = x.send(alice)

In [101]:
bob._objects

{18707345234: tensor([1, 2, 3, 4, 5]), 23501687335: tensor([[1., 1.],
         [0., 1.]], requires_grad=True), 56830104229: tensor([[1.],
         [1.]], requires_grad=True)}

In [104]:
alice._objects

{8730109510: tensor([1, 1, 1, 1, 1]), 48401270218: tensor([[1., 0.],
         [0., 0.]], requires_grad=True), 88756959426: tensor([[0.],
         [0.]], requires_grad=True)}

In [0]:
y = x + x

In [106]:
y

(Wrapper)>[PointerTensor | me:81853863986 -> bob:53151339063]

In [107]:
bob._objects

{18707345234: tensor([1, 2, 3, 4, 5]),
 18929630623: tensor([ 2,  4,  6,  8, 10]),
 23501687335: tensor([[1., 1.],
         [0., 1.]], requires_grad=True),
 53151339063: tensor([ 2,  4,  6,  8, 10]),
 56830104229: tensor([[1.],
         [1.]], requires_grad=True)}

In [108]:
alice._objects

{8730109510: tensor([1, 1, 1, 1, 1]), 48401270218: tensor([[1., 0.],
         [0., 0.]], requires_grad=True), 88756959426: tensor([[0.],
         [0.]], requires_grad=True)}

In [0]:
jon = sy.VirtualWorker(hook, id="jon")

In [0]:
bob.clear_objects()
alice.clear_objects()

x = th.tensor([1,2,3,4,5]).send(bob).send(alice)

In [111]:
bob._objects

{17985641543: tensor([1, 2, 3, 4, 5])}

In [112]:
alice._objects

{80773985922: (Wrapper)>[PointerTensor | alice:80773985922 -> bob:17985641543]}

In [113]:
x = x.get()
x

(Wrapper)>[PointerTensor | me:80773985922 -> bob:17985641543]

In [114]:
bob._objects

{17985641543: tensor([1, 2, 3, 4, 5])}

In [0]:
alice._objects

In [115]:
x = x.get()
x

tensor([1, 2, 3, 4, 5])

In [116]:

bob._objects

{}

In [0]:
bob.clear_objects()
alice.clear_objects()

x = th.tensor([1,2,3,4,5]).send(bob).send(alice)

In [118]:
bob._objects

{40565336952: tensor([1, 2, 3, 4, 5])}

In [119]:
alice._objects

{16407864782: (Wrapper)>[PointerTensor | alice:16407864782 -> bob:40565336952]}

In [0]:
del x

In [121]:
bob._objects

{}

In [122]:

alice._objects

{}

# Pointer Chain Operations

In [123]:

bob.clear_objects()
alice.clear_objects()

<VirtualWorker id:alice #objects:0>

In [0]:
x = th.tensor([1,2,3,4,5]).send(bob)

In [125]:
bob._objects

{40755983815: tensor([1, 2, 3, 4, 5])}

In [126]:
alice._objects

{}

In [127]:
x.move(alice)

(Wrapper)>[PointerTensor | me:33148388278 -> alice:33148388278]

In [129]:
bob._objects

{}

In [130]:
alice._objects

{33148388278: tensor([1, 2, 3, 4, 5])}

In [0]:
x = th.tensor([1,2,3,4,5]).send(bob).send(alice)

In [134]:
bob._objects

{25367150992: tensor([1, 2, 3, 4, 5])}

In [135]:
alice._objects

{33148388278: tensor([1, 2, 3, 4, 5]),
 44047793470: (Wrapper)>[PointerTensor | alice:44047793470 -> bob:25367150992]}

In [136]:
x.remote_get()

(Wrapper)>[PointerTensor | me:90305239978 -> alice:44047793470]

In [137]:
bob._objects

{}

In [138]:
alice._objects

{33148388278: tensor([1, 2, 3, 4, 5]), 44047793470: tensor([1, 2, 3, 4, 5])}

In [139]:
x.move(bob)

(Wrapper)>[PointerTensor | me:90305239978 -> bob:90305239978]

In [140]:
x

(Wrapper)>[PointerTensor | me:90305239978 -> bob:90305239978]

In [142]:
bob._objects

{90305239978: tensor([1, 2, 3, 4, 5])}

In [143]:
alice._objects

{33148388278: tensor([1, 2, 3, 4, 5])}